<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>dotnet_aspnet_console</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\dotnet-aspnet-infrastructure-memory\dotnet-aspnet-infrastructure-memory.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="IServices\" />
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
